version: '3'
services:
  web-db:
    image: mongo:4.2.2
    environment:
      MONGO_INITDB_DATABASE: tinyurl
    ports:
      - 27017:27017
  backend:
    image: urltiny-web-backend:latest
    environment:
      MONGODB_URI: mongodb://web-db:27017/tinyurl
    ports:
      - 8080:8080